-- LIVE 메타 초기화 — 역할·권한 (QA rolePermissions.json 기준)
-- 생성: npx tsx backend/src/scripts/generateLiveMetaRolesPermissionsSql.ts
-- QA roles.str_code·str_display_name 이 다르면 scripts/export_qa_meta_for_live.sh 로 roles 덮어쓸 것

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM role_permissions;
DELETE FROM roles;

INSERT INTO roles (n_id, str_code, str_display_name, str_description, b_is_system, dt_created_at, dt_updated_at) VALUES
	(1, 'admin', '관리자', '전체 시스템 관리 권한', 1, '2026-05-22 18:16:54.944000', '2026-05-22 18:16:54.944000'),
	(2, 'dba', 'DBA', 'DB 쿼리 실행 전담', 1, '2026-05-22 18:16:54.944000', '2026-05-22 18:16:54.944000'),
	(3, 'game_manager', 'GM', '게임 운영 관리자', 1, '2026-05-22 18:16:54.944000', '2026-05-22 18:16:54.944000'),
	(4, 'game_designer', '기획자', '이벤트 기획 및 생성', 1, '2026-05-22 18:16:54.944000', '2026-05-22 18:16:54.944000'),
	(5, 'operator', '운영', 'QA 커스텀 역할(n_id=5) — QA roles와 다르면 export 스크립트로 덮어쓸 것', 0, '2026-05-22 18:16:54.944000', '2026-05-22 18:16:54.944000'),
	(6, 'guest', '승인 대기(GUEST)', '가입 시 부여(로그인은 승인 후)', 1, '2026-05-22 18:16:54.944000', '2026-05-22 18:16:54.944000'),
	(7, 'viewer', '열람', 'QA 커스텀 역할(n_id=7) — QA roles와 다르면 export 스크립트로 덮어쓸 것', 0, '2026-05-22 18:16:54.944000', '2026-05-22 18:16:54.944000');

INSERT INTO role_permissions (n_role_id, str_permission) VALUES
	(4, 'product.view'),
	(4, 'event_template.view'),
	(4, 'my_dashboard.view'),
	(4, 'instance.view'),
	(4, 'instance.create'),
	(4, 'event_template.create'),
	(4, 'my_dashboard.detail'),
	(4, 'my_dashboard.edit'),
	(4, 'my_dashboard.request_confirm'),
	(4, 'my_dashboard.request_qa'),
	(4, 'my_dashboard.verify_qa'),
	(4, 'my_dashboard.request_qa_rereq'),
	(4, 'my_dashboard.verify_live'),
	(4, 'my_dashboard.request_live_rereq'),
	(4, 'my_dashboard.hide'),
	(4, 'my_dashboard.request_live'),
	(1, 'product.view'),
	(1, 'event_template.view'),
	(1, 'instance.create'),
	(1, 'product.create'),
	(1, 'product.edit'),
	(1, 'product.delete'),
	(1, 'event_template.create'),
	(1, 'event_template.edit'),
	(1, 'event_template.delete'),
	(1, 'user.view'),
	(1, 'user.create'),
	(1, 'user.edit'),
	(1, 'user.delete'),
	(1, 'user.reset_password'),
	(1, 'db_connection.view'),
	(1, 'db_connection.create'),
	(1, 'db_connection.edit'),
	(1, 'db_connection.delete'),
	(1, 'db_connection.test'),
	(1, 'my_dashboard.edit'),
	(1, 'my_dashboard.request_confirm'),
	(1, 'my_dashboard.request_qa'),
	(1, 'my_dashboard.request_qa_rereq'),
	(1, 'my_dashboard.execute_qa'),
	(1, 'my_dashboard.query_edit'),
	(1, 'my_dashboard.confirm'),
	(1, 'my_dashboard.verify_qa'),
	(1, 'my_dashboard.request_live'),
	(1, 'my_dashboard.request_live_rereq'),
	(1, 'my_dashboard.execute_live'),
	(1, 'my_dashboard.verify_live'),
	(1, 'role.view'),
	(1, 'role.create'),
	(1, 'role.edit'),
	(1, 'role.delete'),
	(1, 'role.edit_permissions'),
	(1, 'my_dashboard.hide'),
	(1, 'dashboard.view'),
	(1, 'my_dashboard.view'),
	(1, 'my_dashboard.detail'),
	(1, 'instance.view'),
	(1, 'my_dashboard.delete_instance'),
	(1, 'activity.view'),
	(1, 'ui_settings.manage'),
	(5, 'dashboard.view'),
	(5, 'product.view'),
	(5, 'event_template.view'),
	(5, 'event_template.create'),
	(5, 'event_template.edit'),
	(5, 'db_connection.view'),
	(5, 'db_connection.test'),
	(5, 'user.view'),
	(5, 'role.view'),
	(5, 'activity.view'),
	(5, 'my_dashboard.view'),
	(5, 'my_dashboard.detail'),
	(5, 'my_dashboard.edit'),
	(5, 'my_dashboard.confirm'),
	(5, 'my_dashboard.query_edit'),
	(5, 'my_dashboard.execute_qa'),
	(5, 'my_dashboard.execute_live'),
	(5, 'my_dashboard.hide'),
	(5, 'instance.view'),
	(5, 'instance.create'),
	(5, 'instance.delete_own'),
	(1, 'activity.clear'),
	(6, 'my_dashboard.view'),
	(1, 'user.approve'),
	(2, 'my_dashboard.view'),
	(2, 'instance.execute_qa'),
	(2, 'instance.execute_live'),
	(2, 'my_dashboard.detail'),
	(2, 'my_dashboard.confirm'),
	(2, 'my_dashboard.execute_qa'),
	(2, 'my_dashboard.execute_live'),
	(2, 'event_template.view'),
	(2, 'event_template.confirm'),
	(3, 'my_dashboard.view'),
	(3, 'product.view'),
	(3, 'event_template.view'),
	(3, 'instance.create'),
	(3, 'my_dashboard.request_confirm'),
	(3, 'my_dashboard.request_qa'),
	(3, 'my_dashboard.request_qa_rereq'),
	(3, 'my_dashboard.verify_qa'),
	(3, 'my_dashboard.request_live'),
	(3, 'my_dashboard.request_live_rereq'),
	(3, 'my_dashboard.verify_live'),
	(3, 'my_dashboard.hide'),
	(3, 'instance.view'),
	(3, 'my_dashboard.edit'),
	(3, 'my_dashboard.detail'),
	(3, 'dashboard.view'),
	(3, 'instance.delete_own'),
	(7, 'my_dashboard.view');

SET FOREIGN_KEY_CHECKS = 1;
